version: '2'
services:
    albanjarapplication-app:
        image: albanjarapplication
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://albanjarapplication-mysql:3306/albanjarapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    albanjarapplication-mysql:
        extends:
            file: mysql.yml
            service: albanjarapplication-mysql
